name       : networkmanager-vpnc
version    : 1.2.4
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/NetworkManager-vpnc/1.2/NetworkManager-vpnc-1.2.4.tar.xz : 39c7516418e90208cb534c19628ce40fd50eba0a08b2ebaef8da85720b10fb05
license    : GPL-2.0
component  : network.base
summary    : VPNC plugin for Network Manager
description: |
    VPNC Plugin for Network Manager
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libnm)
rundeps    :
    - vpnc
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-check-usr-bin-vpnc-as-well-since-that-is-w.patch
    %configure
build      : |
    %make
install    : |
    %make_install
