name       : networkmanager-vpnc
version    : 1.2.8
release    : 18
source     :
    - https://download.gnome.org/sources/NetworkManager-vpnc/1.2/NetworkManager-vpnc-1.2.8.tar.xz : d65e31aa53c8fdc3fde7ef84a4daa979a605c23fd31ceff647bf7eaaa99afbcc
license    : GPL-2.0-or-later
component  : network.base
summary    : VPNC plugin for Network Manager
description: |
    VPNC Plugin for Network Manager
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
rundeps    :
    - vpnc
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-check-usr-bin-vpnc-as-well-since-that-is-w.patch
    %patch -p1 < $pkgfiles/0001-build-disable-libnm-glib-support-by-default.patch
    # dbus-1 should be moved out of etc, so change sysconfdir
    %reconfigure --sysconfdir=/usr/share --with-gtk4
build      : |
    %make
install    : |
    %make_install
