name       : networkmanager-vpnc
version    : 1.2.6
release    : 11
source     :
    - https://download.gnome.org/sources/NetworkManager-vpnc/1.2/NetworkManager-vpnc-1.2.6.tar.xz : de4fd059c4c08365a40b32b6f6fad9674f556724b4bbeb1f9d4473ac19a745cb
license    : GPL-2.0
component  : network.base
summary    : VPNC plugin for Network Manager
description: |
    VPNC Plugin for Network Manager
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
rundeps    :
    - vpnc
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-check-usr-bin-vpnc-as-well-since-that-is-w.patch
    %patch -p1 < $pkgfiles/0001-build-disable-libnm-glib-support-by-default.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
